version: '3'

services:
  backend:
    build:
      context: ./backend/
    tty: true
    command: bash -c '
      python3 manage.py migrate
      && python3 manage.py loaddata shipments/initial_data.json
      && python3 manage.py runserver 0.0.0.0:8000
      '
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend/
    ports:
      - "5173:5173"
    command: bash -c 'sleep 5 && npm run dev'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - mynetwork

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - pg_data:/var/lib/postgres/data/pg_data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pg_data: